// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY3PO2DlPLZi5EA61rgSKLBIM1bkcN8sA',
    appId: '1:491582290615:web:141c51637473acbcd3ab32',
    messagingSenderId: '491582290615',
    projectId: 'chat-bot-abfba',
    authDomain: 'chat-bot-abfba.firebaseapp.com',
    storageBucket: 'chat-bot-abfba.appspot.com',
    measurementId: 'G-Z01X1NDKVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeUSlamhOJHQxs31xPj2YVFgYZmEkbED4',
    appId: '1:491582290615:android:b1df080ea2057bb7d3ab32',
    messagingSenderId: '491582290615',
    projectId: 'chat-bot-abfba',
    storageBucket: 'chat-bot-abfba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkKfc7RY3uOIjRCSNLFQ1CJd1gNTnrJcw',
    appId: '1:491582290615:ios:31e15fe820ab7332d3ab32',
    messagingSenderId: '491582290615',
    projectId: 'chat-bot-abfba',
    storageBucket: 'chat-bot-abfba.appspot.com',
    iosBundleId: 'com.example.chatBot',
  );
}
